### ISSUE TITLE
CHALLONGE_API_URL has changed

### ISSUE THREAD

**Issue by lhayhurst** [russ-/pychallonge#10]
should be (api.py):

CHALLONGE_API_URL = "api.challonge.com/v1/"

**Comment by russellvt** [comment]
I'm just starting to look at this code for my own use, and maybe fixing a few outstanding issues. But, it's looking as-thought this was fixed, prior to you filing this issue. Can you confirm if you think this is still an issue?

**Comment by lhayhurst** [comment]
hi! I retired my use of the challenge Api about a year ago and thus can’t comment on whether or not it has been fixed.

Good luck!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by russellvt** [comment]
You should likely close this request, then... I've now moved to @ZEDGR's [fork](https://github.com/ZEDGR/pychal), which is more-useful/current.
Looking at it, it appears you were just commenting on the description... and I've fixed it on [my own fork](https://github.com/russellvt/pychal) (current with @ZEDGR's).
