### ISSUE TITLE
Unable to challonge.matches.index() for tournaments that are still pending

### ISSUE THREAD

**Issue by Luckstruck9** [russ-/pychallonge#16]
I am unable to get the list of matches for tournaments that are still pending. Is this something that is prevented by Challonge itself?

**Comment by ZEDGR** [comment]
Hi @Luckstruck9

As far as I know this module is not maintained anymore and as you can see the latest commit is from 2015.

If you want to use a similar module you can check out [my fork ](https://github.com/ZEDGR/pychal). Also I have made a test and it returned the matches that are still pending correctly.
