### ISSUE TITLE
Unable to install package on PyCharm

### ISSUE THREAD

**Issue by soullessoni** [russ-/pychallonge#17]
> pip install -e git+http://github.com/russ-/pychallonge#egg=pychallonge
Obtaining pychallonge from git+http://github.com/russ-/pychallonge#egg=pychallonge
  Cloning http://github.com/russ-/pychallonge to c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\adrien\pycharmprojects\flaskproject\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\adrien\\pycharmprojects\\flaskproject\\venv\\src\\pychallonge\\setup.py'"'"'; _
_file__='"'"'c:\\users\\adrien\\pycharmprojects\\flaskproject\\venv\\src\\pychallonge\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code
, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Adrien\AppData\Local\Temp\pip-pip-egg-info-hudrk2z0'
         cwd: c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge\setup.py", line 2, in <module>
        import challonge
      File "c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge\challonge\__init__.py", line 4, in <module>
        from challonge import tournaments, matches, participants
      File "c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge\challonge\tournaments.py", line 1, in <module>
        from challonge import api
      File "c:\users\adrien\pycharmprojects\flaskproject\venv\src\pychallonge\challonge\api.py", line 2, in <module>
        import iso8601
    ModuleNotFoundError: No module named 'iso8601'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

> py --version
Python 3.9.0

**Comment by ZEDGR** [comment]
Hi @soullessoni 

Can you try using this [fork](https://github.com/ZEDGR/pychal) instead? As far as I know this module is not maintained anymore and as you can see the latest commit is from 2015.
