### ISSUE TITLE
Correct timezone in start_time

### ISSUE THREAD

**Issue by SlavWolf** [russ-/pychallonge#18]
What's the correct way of providing timezone for start_time?
When I use:
`datetime.datetime(int(year), int(month), int(day), int(hours), int(minutes), 0, 0, tzinfo=pytz.timezone('Europe/London'))`
it defaults to -05.00 timezone anyway.

**Comment by russ-** [comment]
I am archiving this project since it has not been maintained in several years.

Please try using https://github.com/ZEDGR/pychallonge instead and, if you can still reproduce the problem, file a new issue there.
