### ISSUE TITLE
Python 3.3

### ISSUE THREAD

**Issue by oddballbutler** [russ-/pychallonge#4]
Does pychallonge work with Python 3.3? I keep getting this error when trying to install

```
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "E:\pychallonge\src\pychallonge\setup.py", line 2, in <module>
        import challonge
      File ".\challonge\__init__.py", line 4, in <module>
        import tournaments, matches, participants
    ImportError: No module named 'tournaments'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "E:\pychallonge\src\pychallonge\setup.py", line 2, in <module>

    import challonge

  File ".\challonge\__init__.py", line 4, in <module>

    import tournaments, matches, participants

ImportError: No module named 'tournaments'
```

I have successfully installed and used pychallonge with Python 2.7

**Comment by iGeekuPlay** [comment]
I just tried to run the tests on python 3.6.3 and got the following:
`
..........F.F......
======================================================================
FAIL: test_index (__main__.TournamentsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 51, in test_index
    self.assertEqual(self.t, ts[0])
AssertionError: {'id'[307 chars] 15, 21, 13, 58, tzinfo=<iso8601.Utc>), 'updat[2100 chars]alse} != {'id'[307 chars] 15, 17, 13, 58, tzinfo=<FixedOffset '-04:00' [2206 chars]alse}
Diff is 3070 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_index_filter_by_state (__main__.TournamentsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 57, in test_index_filter_by_state
    self.assertEqual(self.t, ts[0])
AssertionError: {'id'[1968 chars]'\n  ', 'auto-assign-stations': None, 'only-st[521 chars]alse} != {'id'[1968 chars]'\n    ', 'auto-assign-stations': None, 'only-[523 chars]alse}
Diff is 2880 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 19 tests in 37.008s

FAILED (failures=2)
`

**Comment by iGeekuPlay** [comment]
> I just tried to run the tests on python 3.7.3 and got the following:
> 
> ```
> ..........F.F......
> ======================================================================
> FAIL: test_index (__main__.TournamentsTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests.py", line 51, in test_index
>     self.assertEqual(self.t, ts[0])
> AssertionError: {'id'[307 chars] 15, 21, 13, 58, tzinfo=<iso8601.Utc>), 'updat[2100 chars]alse} != {'id'[307 chars] 15, 17, 13, 58, tzinfo=<FixedOffset '-04:00' [2206 chars]alse}
> Diff is 3070 characters long. Set self.maxDiff to None to see it.
> 
> ======================================================================
> FAIL: test_index_filter_by_state (__main__.TournamentsTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests.py", line 57, in test_index_filter_by_state
>     self.assertEqual(self.t, ts[0])
> AssertionError: {'id'[1968 chars]'\n  ', 'auto-assign-stations': None, 'only-st[521 chars]alse} != {'id'[1968 chars]'\n    ', 'auto-assign-stations': None, 'only-[523 chars]alse}
> Diff is 2880 characters long. Set self.maxDiff to None to see it.
> 
> ----------------------------------------------------------------------
> Ran 19 tests in 37.008s
> 
> FAILED (failures=2)
> ```

the tests are failing due to a extra space after the `\n` in the output as follows:
```non-elimination-tournament-data": "\n  ",```

**Comment by ZEDGR** [comment]
@iGeekuPlay If you want to try my fork because I think @russ- is not maintaining this project anymore.

https://github.com/ZEDGR/pychal

**Comment by iGeekuPlay** [comment]
@ZEDGR  thanks ran and got the following.
```
......ss.....sss.....s..................
----------------------------------------------------------------------
Ran 40 tests in 77.261s

OK (skipped=6)
```

**Comment by ZEDGR** [comment]
@iGeekuPlay Thanks for using my module 

The output that you see is normal because the attachment endpoints are not working and returning Internal Server Error. These errors are from Challonge and I have reported them in the past. Therefore in the tests.py I am skipping those 6 tests. For more info read the section API Issues at the README file

https://github.com/ZEDGR/pychal#api-issues
