### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by lhayhurst** [russ-/pychallonge#8]
great module!  thank you.  

is attachments on the roadmap?

http://api.challonge.com/v1/documents/match_attachments/index

**Comment by ZEDGR** [comment]
I have try to implement the attachments but I am facing problems from the challonge API. I am receiving 500 Internal Server Error. I have reported this to the Challonge team through email, the knowledge base, facebook official page and twitter many times but no response. I am very frustrated about this.

**Comment by lhayhurst** [comment]
hi, couple of questions. 1) are you able to get other data (participants, matches, etc) without getting a 500? 2) are you trying to PUT attachments, or just GET them? 3) are you using this github module (pychallonge)? cheers

**Comment by ZEDGR** [comment]
Yes I forgot to mention :P I have an updated [fork](https://github.com/ZEDGR/pychal)

**Comment by lhayhurst** [comment]
sorry, so I don't understand! Are you saying that you have an updated fork that is trying to POST attachments?

**Comment by ZEDGR** [comment]
I tried in my fork to implement the attachments but it seems there is a problem with the Challonge API. That's the whole story. So to answer your first question "is attachments on the roadmap?" I am waiting the Challonge team to fix their API or If you like I can implement Index, Show, Destroy for attachments endpoints.

**Comment by lhayhurst** [comment]
Ah, I see. I suspect that he hasn't implemented POST for attachments which is why you are getting the 500 error :-( GET is working fine at least :-)

**Comment by ZEDGR** [comment]
@corneldm when are you going to fix the attachments create and update endpoints?
